- name: Build with Gradle
  run: |
    chmod +x gradlew
    ./gradlew build --no-daemon
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd $GITHUB_WORKSPACE
          gradle build --no-daemon

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: HIGOR-CLIENT-CORE
          path: build/libs/*.jar
